# Generated by Django 5.2.14 on 2026-05-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='creator_profiles/'),
        ),
    ]
