# Generated by Django 5.2.14 on 2026-05-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppv', '0002_creator_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Bitcoin, USDT (TRC20)', max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='crypto_address',
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='giftcard_details',
            field=models.TextField(blank=True, help_text='Instructions for gift card payments'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('crypto', 'Crypto'), ('gift_card', 'Gift Card')], max_length=20),
        ),
    ]
