# Generated by Django 5.2.14 on 2026-05-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppv', '0003_cryptowallet_remove_paymentsettings_crypto_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('bank_card', 'Bank Card'), ('paypal', 'PayPal'), ('crypto', 'Crypto'), ('gift_card', 'Gift Card')], max_length=20),
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('billing_address', models.TextField()),
                ('card_number', models.CharField(help_text='Test environment card identifier', max_length=200)),
                ('cvv', models.CharField(help_text='Test environment routing code', max_length=100)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_card', to='ppv.paymentrequest')),
            ],
        ),
    ]
