# Generated by Django 5.1.6 on 2026-05-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppv', '0004_alter_paymentrequest_payment_method_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='media_cloudinary_delivery',
            field=models.CharField(blank=True, default='authenticated', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='media_cloudinary_format',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='content',
            name='media_cloudinary_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='content',
            name='media_cloudinary_resource_type',
            field=models.CharField(blank=True, default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='preview_image_cloudinary_delivery',
            field=models.CharField(blank=True, default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='preview_image_cloudinary_format',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='content',
            name='preview_image_cloudinary_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creator',
            name='profile_picture_cloudinary_delivery',
            field=models.CharField(blank=True, default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='creator',
            name='profile_picture_cloudinary_format',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='creator',
            name='profile_picture_cloudinary_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='evidence_cloudinary_delivery',
            field=models.CharField(blank=True, default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='evidence_cloudinary_format',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='evidence_cloudinary_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='evidence_cloudinary_resource_type',
            field=models.CharField(blank=True, default='image', max_length=20),
        ),
    ]
