services:
  - type: web
    name: onlylovablefans
    runtime: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    releaseCommand: python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "onlylovablefans.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://onlylovablefans.onrender.com"
      - key: SETUP_TOKEN
        generateValue: true
      - key: CLOUDINARY_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: onlylovablefans-db
          property: connectionString

databases:
  - name: onlylovablefans-db
    plan: free
